name: cc_uffs
description: Aplicativo móvel para uso de alunos, professores e técnicos do curso de Ciência da Computação da UFFS.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  flutter_clean_architecture: ^1.0.5
  url_launcher: ^5.1.6
  pedantic: ^1.5.0
  navigate: ^1.0.0
  rxdart: ^0.22.4
  flutter_spinkit: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/logo-branco.png
    - assets/imgs/logo-verde.png
